import Head from 'next/head'
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import UsersTable from '../components/UsersTable';
import AppNavbar from '../components/AppNavbar';

import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';
import styles from '../styles/IndexPage.module.css'

export default function IndexPage() {
  return (
      <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            <Container>
              <Row>
                <Col>
                  <AppNavbar />
                </Col>
              </Row>
              <Row>
                <Col>
                  <UsersTable />
                </Col>
              </Row>
            </Container>
          </main>
      </>
  );
}